config/routes.rb
Talkroom::Application.routes.draw do

  resources :point_consumptions

  resources :inquiries

  resources :buying_histories

  resources :ios_transactions

  resources :ca_rewards

  resources :friends

  resources :lists
  match "/get_all_users" => "api#get_all_users"#デバッグ用
  match "/get_recent_rooms" => "api#get_recent_rooms"
  match "/get_room_summary_data" => "api#get_room_summary_data"
  match "/get_search_users" => "api#get_search_users"
  match "/get_oneside_rooms" => "api#get_oneside_rooms"
  match "/get_bothside_rooms" => "api#get_bothside_rooms"
  match "/get_detail_profile" => "api#get_detail_profile"
  match "/get_user_rooms" => "api#get_user_rooms"
  match "/get_user_profile" => "api#get_user_profile"
  match "/get_room_message" => "api#get_room_message"
  match "/get_visits" => "api#get_visits"
  match "/get_point" => "api#get_point"
  match "/consume_point" => "api#consume_point"
  match "/change_private_room" => "api#change_private_room"
  
  match "/update_profile" => "api#update_profile"
  match "/update_detail_profile" => "api#update_detail_profile" 
  
  match "/create_message" => "api#create_message"
  match "/create_account" => "api#create_account"
  match "/create_friends" => "api#create_friends"
  match "/upload_image" => "api#upload_image"
  match "/upload_fb_image" => "api#upload_fb_image"
  
  match "/check_login" => "api#check_login"
  match "/car_pointback" => "api#car_pointback"
  match "/send_mail" => "api#send_mail"
  match "/send_report" => "api#send_report"
  
  match "/verify_receipt" => "api#verify_receipt", :defaults => {:format => :json}
  
  match "/example_token" => "api#example_token"
  
  resources :visits

  resources :rooms

  resources :messages

  
  
  root :to => 'welcome#index' 
  get 'lists', :to=> 'lists#index', :as=>:user_root

  devise_for :lists, :controllers => { :omniauth_callbacks => "lists/omniauth_callbacks" }
  
  devise_scope :list do
    get 'sign_in.list', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  

end

app/models/friend.rb
class Friend < ActiveRecord::Base
  attr_accessible :fb_gender, :fb_uid, :list_id
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  # GET /friends
  # GET /friends.json
  def index
    @friends = Friend.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @friends }
    end
  end

  # GET /friends/1
  # GET /friends/1.json
  def show
    @friend = Friend.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @friend }
    end
  end

  # GET /friends/new
  # GET /friends/new.json
  def new
    @friend = Friend.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @friend }
    end
  end

  # GET /friends/1/edit
  def edit
    @friend = Friend.find(params[:id])
  end

  # POST /friends
  # POST /friends.json
  def create
    @friend = Friend.new(params[:friend])

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, :notice => 'Friend was successfully created.' }
        format.json { render :json => @friend, :status => :created, :location => @friend }
      else
        format.html { render :action => "new" }
        format.json { render :json => @friend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /friends/1
  # PUT /friends/1.json
  def update
    @friend = Friend.find(params[:id])

    respond_to do |format|
      if @friend.update_attributes(params[:friend])
        format.html { redirect_to @friend, :notice => 'Friend was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @friend.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1
  # DELETE /friends/1.json
  def destroy
    @friend = Friend.find(params[:id])
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_for(@friend) do |f| %>
  <% if @friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
      <% @friend.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_id %><br />
    <%= f.number_field :list_id %>
  </div>
  <div class="field">
    <%= f.label :fb_uid %><br />
    <%= f.number_field :fb_uid %>
  </div>
  <div class="field">
    <%= f.label :fb_gender %><br />
    <%= f.text_field :fb_gender %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render 'form' %>

<%= link_to 'Show', @friend %> |
<%= link_to 'Back', friends_path %>

app/views/friends/index.html.erb
<h1>Listing friends</h1>

<table>
  <tr>
    <th>List</th>
    <th>Fb uid</th>
    <th>Fb gender</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @friends.each do |friend| %>
  <tr>
    <td><%= friend.list_id %></td>
    <td><%= friend.fb_uid %></td>
    <td><%= friend.fb_gender %></td>
    <td><%= link_to 'Show', friend %></td>
    <td><%= link_to 'Edit', edit_friend_path(friend) %></td>
    <td><%= link_to 'Destroy', friend, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Friend', new_friend_path %>

app/views/friends/new.html.erb
<h1>New friend</h1>

<%= render 'form' %>

<%= link_to 'Back', friends_path %>

app/views/friends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List:</b>
  <%= @friend.list_id %>
</p>

<p>
  <b>Fb uid:</b>
  <%= @friend.fb_uid %>
</p>

<p>
  <b>Fb gender:</b>
  <%= @friend.fb_gender %>
</p>


<%= link_to 'Edit', edit_friend_path(@friend) %> |
<%= link_to 'Back', friends_path %>