config/routes.rb
Talkroom::Application.routes.draw do

  resources :point_consumptions

  resources :inquiries

  resources :buying_histories

  resources :ios_transactions

  resources :ca_rewards

  resources :friends

  resources :lists
  match "/get_all_users" => "api#get_all_users"#デバッグ用
  match "/get_recent_rooms" => "api#get_recent_rooms"
  match "/get_room_summary_data" => "api#get_room_summary_data"
  match "/get_search_users" => "api#get_search_users"
  match "/get_oneside_rooms" => "api#get_oneside_rooms"
  match "/get_bothside_rooms" => "api#get_bothside_rooms"
  match "/get_detail_profile" => "api#get_detail_profile"
  match "/get_user_rooms" => "api#get_user_rooms"
  match "/get_user_profile" => "api#get_user_profile"
  match "/get_room_message" => "api#get_room_message"
  match "/get_visits" => "api#get_visits"
  match "/get_point" => "api#get_point"
  match "/consume_point" => "api#consume_point"
  match "/change_private_room" => "api#change_private_room"
  
  match "/update_profile" => "api#update_profile"
  match "/update_detail_profile" => "api#update_detail_profile" 
  
  match "/create_message" => "api#create_message"
  match "/create_account" => "api#create_account"
  match "/create_friends" => "api#create_friends"
  match "/upload_image" => "api#upload_image"
  match "/upload_fb_image" => "api#upload_fb_image"
  
  match "/check_login" => "api#check_login"
  match "/car_pointback" => "api#car_pointback"
  match "/send_mail" => "api#send_mail"
  match "/send_report" => "api#send_report"
  
  match "/verify_receipt" => "api#verify_receipt", :defaults => {:format => :json}
  
  match "/example_token" => "api#example_token"
  
  resources :visits

  resources :rooms

  resources :messages

  
  
  root :to => 'welcome#index' 
  get 'lists', :to=> 'lists#index', :as=>:user_root

  devise_for :lists, :controllers => { :omniauth_callbacks => "lists/omniauth_callbacks" }
  
  devise_scope :list do
    get 'sign_in.list', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  attr_accessible :visitor_list_id, :visitat_list_id
  
  #==========
  #アソシエーションの設定
  #==========
  #belongs_to (オブジェクト名, :class_name => 参照先クラス名, :foreign_key => 接続フィールド名)
  belongs_to :visitor, :class_name => 'List', :foreign_key => 'visitor_list_id'
  belongs_to :visitat, :class_name => 'List', :foreign_key => 'visitat_list_id'
  
  
  #==========
  #バリデーションの設定
  #==========
  
  validates :visitor_list_id,
    :presence => true
    
  validates :visitat_list_id,
    :presence => true
    
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  # GET /visits
  # GET /visits.json
  
  #サービス開始時にはコメントアウトを外す
  #before_filter :check_logined
  
  def index
    @visits = Visit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @visits }
    end
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @visit = Visit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @visit }
    end
  end

  # GET /visits/new
  # GET /visits/new.json
  def new
    @visit = Visit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @visit }
    end
  end

  # GET /visits/1/edit
  def edit
    @visit = Visit.find(params[:id])
  end

  # POST /visits
  # POST /visits.json
  def create
    @visit = Visit.new(params[:visit])

    respond_to do |format|
      if @visit.save
        format.html { redirect_to @visit, :notice => 'Visit was successfully created.' }
        format.json { render :json => @visit, :status => :created, :location => @visit }
      else
        format.html { render :action => "new" }
        format.json { render :json => @visit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /visits/1
  # PUT /visits/1.json
  def update
    @visit = Visit.find(params[:id])

    respond_to do |format|
      if @visit.update_attributes(params[:visit])
        format.html { redirect_to @visit, :notice => 'Visit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @visit.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    @visit = Visit.find(params[:id])
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_form.html.erb
<%= form_for(@visit) do |f| %>
  <% if @visit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
      <% @visit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :visitor_list_id %><br />
    <%= f.number_field :visitor_list_id %>
  </div>
  <div class="field">
    <%= f.label :visitat_list_id %><br />
    <%= f.number_field :visitat_list_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render 'form' %>

<%= link_to 'Show', @visit %> |
<%= link_to 'Back', visits_path %>

app/views/visits/index.html.erb
<h1>Listing visits</h1>

<table>
  <tr>
  	<th>ID</th>
    <th>Visitor</th>
    <th>Visit at</th>
    <th>created_at</th>
    <th>updated_at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @visits.each do |visit| %>
  <tr>
  	<td><%= visit.id %></td>
    <td><%= visit.visitor.nickname %></td>
    <td><%= visit.visitat.nickname %></td>
    <td><%= visit.created_at %></td>
    <td><%= visit.updated_at %></td>
    <td><%= link_to 'Show', visit %></td>
    <td><%= link_to 'Edit', edit_visit_path(visit) %></td>
    <td><%= link_to 'Destroy', visit, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Visit', new_visit_path %>

app/views/visits/new.html.erb
<h1>New visit</h1>

<%= render 'form' %>

<%= link_to 'Back', visits_path %>

app/views/visits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>ID:</b>
  <%= @visit.id %>
</p>

<p>
  <b>Visitor:</b>
  <%= @visit.visitor.nickname %>
</p>

<p>
  <b>Visit at:</b>
  <%= @visit.visitat.nickname %>
</p>

<p>
  <b>Created_at</b>
  <%= @visit.created_at %>
</p>

<p>
  <b>Visitor:</b>
  <%= @visit.updated_at %>
</p>

<%= link_to 'Edit', edit_visit_path(@visit) %> |
<%= link_to 'Back', visits_path %>