config/routes.rb
Talkroom::Application.routes.draw do

  resources :point_consumptions

  resources :inquiries

  resources :buying_histories

  resources :ios_transactions

  resources :ca_rewards

  resources :friends

  resources :lists
  match "/get_all_users" => "api#get_all_users"#デバッグ用
  match "/get_recent_rooms" => "api#get_recent_rooms"
  match "/get_room_summary_data" => "api#get_room_summary_data"
  match "/get_search_users" => "api#get_search_users"
  match "/get_oneside_rooms" => "api#get_oneside_rooms"
  match "/get_bothside_rooms" => "api#get_bothside_rooms"
  match "/get_detail_profile" => "api#get_detail_profile"
  match "/get_user_rooms" => "api#get_user_rooms"
  match "/get_user_profile" => "api#get_user_profile"
  match "/get_room_message" => "api#get_room_message"
  match "/get_visits" => "api#get_visits"
  match "/get_point" => "api#get_point"
  match "/consume_point" => "api#consume_point"
  match "/change_private_room" => "api#change_private_room"
  
  match "/update_profile" => "api#update_profile"
  match "/update_detail_profile" => "api#update_detail_profile" 
  
  match "/create_message" => "api#create_message"
  match "/create_account" => "api#create_account"
  match "/create_friends" => "api#create_friends"
  match "/upload_image" => "api#upload_image"
  match "/upload_fb_image" => "api#upload_fb_image"
  
  match "/check_login" => "api#check_login"
  match "/car_pointback" => "api#car_pointback"
  match "/send_mail" => "api#send_mail"
  match "/send_report" => "api#send_report"
  
  match "/verify_receipt" => "api#verify_receipt", :defaults => {:format => :json}
  
  match "/example_token" => "api#example_token"
  
  resources :visits

  resources :rooms

  resources :messages

  
  
  root :to => 'welcome#index' 
  get 'lists', :to=> 'lists#index', :as=>:user_root

  devise_for :lists, :controllers => { :omniauth_callbacks => "lists/omniauth_callbacks" }
  
  devise_scope :list do
    get 'sign_in.list', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  

end

app/models/buying_history.rb
class BuyingHistory < ActiveRecord::Base
  attr_accessible :list_id, :platform, :transaction_id
end

app/controllers/buying_histories_controller.rb
class BuyingHistoriesController < ApplicationController
  # GET /buying_histories
  # GET /buying_histories.json
  def index
    @buying_histories = BuyingHistory.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @buying_histories }
    end
  end

  # GET /buying_histories/1
  # GET /buying_histories/1.json
  def show
    @buying_history = BuyingHistory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @buying_history }
    end
  end

  # GET /buying_histories/new
  # GET /buying_histories/new.json
  def new
    @buying_history = BuyingHistory.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @buying_history }
    end
  end

  # GET /buying_histories/1/edit
  def edit
    @buying_history = BuyingHistory.find(params[:id])
  end

  # POST /buying_histories
  # POST /buying_histories.json
  def create
    @buying_history = BuyingHistory.new(params[:buying_history])

    respond_to do |format|
      if @buying_history.save
        format.html { redirect_to @buying_history, :notice => 'Buying history was successfully created.' }
        format.json { render :json => @buying_history, :status => :created, :location => @buying_history }
      else
        format.html { render :action => "new" }
        format.json { render :json => @buying_history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /buying_histories/1
  # PUT /buying_histories/1.json
  def update
    @buying_history = BuyingHistory.find(params[:id])

    respond_to do |format|
      if @buying_history.update_attributes(params[:buying_history])
        format.html { redirect_to @buying_history, :notice => 'Buying history was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @buying_history.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /buying_histories/1
  # DELETE /buying_histories/1.json
  def destroy
    @buying_history = BuyingHistory.find(params[:id])
    @buying_history.destroy

    respond_to do |format|
      format.html { redirect_to buying_histories_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/buying_histories_helper.rb
module BuyingHistoriesHelper
end

app/views/buying_histories/_form.html.erb
<%= form_for(@buying_history) do |f| %>
  <% if @buying_history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@buying_history.errors.count, "error") %> prohibited this buying_history from being saved:</h2>

      <ul>
      <% @buying_history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :list_id %><br />
    <%= f.number_field :list_id %>
  </div>
  <div class="field">
    <%= f.label :platform %><br />
    <%= f.text_field :platform %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br />
    <%= f.number_field :transaction_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buying_histories/edit.html.erb
<h1>Editing buying_history</h1>

<%= render 'form' %>

<%= link_to 'Show', @buying_history %> |
<%= link_to 'Back', buying_histories_path %>

app/views/buying_histories/index.html.erb
<h1>Listing buying_histories</h1>

<table>
  <tr>
    <th>List</th>
    <th>Platform</th>
    <th>Transaction</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buying_histories.each do |buying_history| %>
  <tr>
    <td><%= buying_history.list_id %></td>
    <td><%= buying_history.platform %></td>
    <td><%= buying_history.transaction_id %></td>
    <td><%= link_to 'Show', buying_history %></td>
    <td><%= link_to 'Edit', edit_buying_history_path(buying_history) %></td>
    <td><%= link_to 'Destroy', buying_history, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Buying history', new_buying_history_path %>

app/views/buying_histories/new.html.erb
<h1>New buying_history</h1>

<%= render 'form' %>

<%= link_to 'Back', buying_histories_path %>

app/views/buying_histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>List:</b>
  <%= @buying_history.list_id %>
</p>

<p>
  <b>Platform:</b>
  <%= @buying_history.platform %>
</p>

<p>
  <b>Transaction:</b>
  <%= @buying_history.transaction_id %>
</p>


<%= link_to 'Edit', edit_buying_history_path(@buying_history) %> |
<%= link_to 'Back', buying_histories_path %>