config/routes.rb
Talkroom::Application.routes.draw do

  resources :point_consumptions

  resources :inquiries

  resources :buying_histories

  resources :ios_transactions

  resources :ca_rewards

  resources :friends

  resources :lists
  match "/get_all_users" => "api#get_all_users"#デバッグ用
  match "/get_recent_rooms" => "api#get_recent_rooms"
  match "/get_room_summary_data" => "api#get_room_summary_data"
  match "/get_search_users" => "api#get_search_users"
  match "/get_oneside_rooms" => "api#get_oneside_rooms"
  match "/get_bothside_rooms" => "api#get_bothside_rooms"
  match "/get_detail_profile" => "api#get_detail_profile"
  match "/get_user_rooms" => "api#get_user_rooms"
  match "/get_user_profile" => "api#get_user_profile"
  match "/get_room_message" => "api#get_room_message"
  match "/get_visits" => "api#get_visits"
  match "/get_point" => "api#get_point"
  match "/consume_point" => "api#consume_point"
  match "/change_private_room" => "api#change_private_room"
  
  match "/update_profile" => "api#update_profile"
  match "/update_detail_profile" => "api#update_detail_profile" 
  
  match "/create_message" => "api#create_message"
  match "/create_account" => "api#create_account"
  match "/create_friends" => "api#create_friends"
  match "/upload_image" => "api#upload_image"
  match "/upload_fb_image" => "api#upload_fb_image"
  
  match "/check_login" => "api#check_login"
  match "/car_pointback" => "api#car_pointback"
  match "/send_mail" => "api#send_mail"
  match "/send_report" => "api#send_report"
  
  match "/verify_receipt" => "api#verify_receipt", :defaults => {:format => :json}
  
  match "/example_token" => "api#example_token"
  
  resources :visits

  resources :rooms

  resources :messages

  
  
  root :to => 'welcome#index' 
  get 'lists', :to=> 'lists#index', :as=>:user_root

  devise_for :lists, :controllers => { :omniauth_callbacks => "lists/omniauth_callbacks" }
  
  devise_scope :list do
    get 'sign_in.list', :to => 'devise/sessions#new', :as => :new_user_session
    get 'sign_in', :to => 'devise/sessions#new', :as => :new_session
    get 'sign_out', :to => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  

end

app/controllers/ios_transactions_controller.rb
class IosTransactionsController < ApplicationController
  # GET /ios_transactions
  # GET /ios_transactions.json
  def index
    @ios_transactions = IosTransaction.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @ios_transactions }
    end
  end

  # GET /ios_transactions/1
  # GET /ios_transactions/1.json
  def show
    @ios_transaction = IosTransaction.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @ios_transaction }
    end
  end

  # GET /ios_transactions/new
  # GET /ios_transactions/new.json
  def new
    @ios_transaction = IosTransaction.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @ios_transaction }
    end
  end

  # GET /ios_transactions/1/edit
  def edit
    @ios_transaction = IosTransaction.find(params[:id])
  end

  # POST /ios_transactions
  # POST /ios_transactions.json
  def create
    @ios_transaction = IosTransaction.new(params[:ios_transaction])

    respond_to do |format|
      if @ios_transaction.save
        format.html { redirect_to @ios_transaction, :notice => 'Ios transaction was successfully created.' }
        format.json { render :json => @ios_transaction, :status => :created, :location => @ios_transaction }
      else
        format.html { render :action => "new" }
        format.json { render :json => @ios_transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /ios_transactions/1
  # PUT /ios_transactions/1.json
  def update
    @ios_transaction = IosTransaction.find(params[:id])

    respond_to do |format|
      if @ios_transaction.update_attributes(params[:ios_transaction])
        format.html { redirect_to @ios_transaction, :notice => 'Ios transaction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @ios_transaction.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /ios_transactions/1
  # DELETE /ios_transactions/1.json
  def destroy
    @ios_transaction = IosTransaction.find(params[:id])
    @ios_transaction.destroy

    respond_to do |format|
      format.html { redirect_to ios_transactions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/ios_transactions_helper.rb
module IosTransactionsHelper
end

app/views/ios_transactions/_form.html.erb
<%= form_for(@ios_transaction) do |f| %>
  <% if @ios_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ios_transaction.errors.count, "error") %> prohibited this ios_transaction from being saved:</h2>

      <ul>
      <% @ios_transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :transaction_id %><br />
    <%= f.text_field :transaction_id %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br />
    <%= f.datetime_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :bvrs %><br />
    <%= f.text_field :bvrs %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ios_transactions/edit.html.erb
<h1>Editing ios_transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @ios_transaction %> |
<%= link_to 'Back', ios_transactions_path %>

app/views/ios_transactions/index.html.erb
<h1>Listing ios_transactions</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Product</th>
    <th>Transaction</th>
    <th>Purchase date</th>
    <th>Bvrs</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ios_transactions.each do |ios_transaction| %>
  <tr>
    <td><%= ios_transaction.type %></td>
    <td><%= ios_transaction.product_id %></td>
    <td><%= ios_transaction.transaction_id %></td>
    <td><%= ios_transaction.purchase_date %></td>
    <td><%= ios_transaction.bvrs %></td>
    <td><%= link_to 'Show', ios_transaction %></td>
    <td><%= link_to 'Edit', edit_ios_transaction_path(ios_transaction) %></td>
    <td><%= link_to 'Destroy', ios_transaction, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Ios transaction', new_ios_transaction_path %>

app/views/ios_transactions/new.html.erb
<h1>New ios_transaction</h1>

<%= render 'form' %>

<%= link_to 'Back', ios_transactions_path %>

app/views/ios_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @ios_transaction.type %>
</p>

<p>
  <b>Product:</b>
  <%= @ios_transaction.product_id %>
</p>

<p>
  <b>Transaction:</b>
  <%= @ios_transaction.transaction_id %>
</p>

<p>
  <b>Purchase date:</b>
  <%= @ios_transaction.purchase_date %>
</p>

<p>
  <b>Bvrs:</b>
  <%= @ios_transaction.bvrs %>
</p>


<%= link_to 'Edit', edit_ios_transaction_path(@ios_transaction) %> |
<%= link_to 'Back', ios_transactions_path %>